### ISSUE TITLE
Won't load node_modules in fork of repository 

### ISSUE THREAD

**Issue by julienlegault** [bubblebooy/Artifact-Javascript#10]
I've got an exact clone of Artifact Javascript trying to run [here](https://julienlegault.github.io/Artifact-Javascript/dist/index.html) but it keeps 404ing on anything stored in node_modules. Do I need to do something with the .gitignore file? It should work because it is the exact clone of your files. Are you running the github page off gh-pages branch or master? Considering it has access to master I would assume master, but I may be wrong there.

**Comment by bubblebooy** [comment]
Ignore the gh-pages branch. My GitHub Pages is being run off the master branch.

**Comment by julienlegault** [comment]
That's what I thought, and my page is also being run off the master branch. There are no differences between our repositories, so I'm really not sure why the node_modules won't load for me.

**Comment by bubblebooy** [comment]
~~Your github.io root is Artifact-Javascript/dist/index.html instead of Artifact-Javascript/index.html.
I do not know how you change that.~~ You can see the problem by comparing the sources tab in the chrome inspector.

edit:
https://julienlegault.github.io/Artifact-Javascript/index.html
correctly works and redirects. weird

**Comment by julienlegault** [comment]
For some reason the .nojekyll file worked this time... I now have a working version, sorry I put a change request on your repository, I can't seem to remove it.
